<?php
define("ROOT",str_replace(DIRECTORY_SEPARATOR."public".DIRECTORY_SEPARATOR."index.php", "", $_SERVER["SCRIPT_FILENAME"]));
define("ROOT_VIEWS",ROOT.DIRECTORY_SEPARATOR."views".DIRECTORY_SEPARATOR);
define("ROOT_LIB",ROOT.DIRECTORY_SEPARATOR."lib".DIRECTORY_SEPARATOR);
define("ROOT_MODELS",ROOT.DIRECTORY_SEPARATOR."models".DIRECTORY_SEPARATOR);
define("ROOT_VIEWS_INC",ROOT_VIEWS."inc".DIRECTORY_SEPARATOR);
define("ROOT_VIEWS_USER", ROOT_VIEWS . "user" . DIRECTORY_SEPARATOR);
define("ROOT_DATA",ROOT.DIRECTORY_SEPARATOR."data".DIRECTORY_SEPARATOR);
define("ROOT_ROUTE",ROOT.DIRECTORY_SEPARATOR."routes".DIRECTORY_SEPARATOR);
define("ROOT_CONFIG",ROOT.DIRECTORY_SEPARATOR."config".DIRECTORY_SEPARATOR);
define("ROOT_LAYOUT",ROOT_VIEWS."layout".DIRECTORY_SEPARATOR);
define("ROOT_PUBLIC",ROOT.DIRECTORY_SEPARATOR."public".DIRECTORY_SEPARATOR);
define("ROOT_PUBLIC_CSS",ROOT_PUBLIC."css".DIRECTORY_SEPARATOR);
define("ROOT_PUBLIC_IMAGES",ROOT_PUBLIC."images".DIRECTORY_SEPARATOR);
define("ROOT_PUBLIC_js",ROOT_PUBLIC."js".DIRECTORY_SEPARATOR);

//le chemin des action de nos formulaires
define("WEB_ROOT","http://localhost:8000/");
//define("WEB_ROOT",str_replace("index.php", "", $_SERVER["SCRIPT_NAME"]));
define("ROOT_CONTROLLERS",WEB_ROOT."controllers");